# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
# Unable to inspect table 'ADM.AccesoOpcBoton'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'ADM.AuditoriaFE'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'ADM.CentroCosto_NegocioSede'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'ADM.DocumentoPagoDetPaqSLI'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'ADM.DocumentoPagoDetalle_2'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'ADM.DocumentoPago_2'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'ADM.Empresa_2'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'ADM.Feriado_2'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'ADM.LineaNegocio_2'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'ADM.LineaNegocio_2Sincronizacion'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'ADM.LiquidacionDetallePos_2'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'ADM.LiquidacionDetallePre_2'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'ADM.Liquidacion_2'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'ADM.OficinaLineaNegocio_2'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'ADM.OficinaLineaNegocio_2Sincronizacion'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'ADM.Oficina_2'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'ADM.ServicioOficinaLineaNegocioComunes_2'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'ADM.ServicioOficinaLineaNegocio_2'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'ADM.ServicioOficinaLineaNegocio_2Sincronizacion'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'ADM.Servicio_2'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'ADM.Servicio_2Sincronizacion'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'ADM.TipoCambio_2'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'ADM_FE.ClaseTributaria'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'ADM_FE.CombinaClaseAfectacion'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'ADM_FE.Desfase'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'ADM_FE.EstadoEvento'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'ADM_FE.Evento'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'ADM_FE.Glosa'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'ADM_FE.Prueba'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'ADM_FE.SolicitudBaja'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'ADM_FE.TipoAfectacion'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'ADM_FE.Ubigeo'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'ADM_FE.UsuarioGrupo'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'AUD.AppCheckerPatio'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'AUD.App_ServicioImagen'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'AUD.AutRetiroPlacaChofer'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'AUD.CambioPlacaChofer'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'AUD.LogsWSApp'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'AUD.OrdenServicioDespachador'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'AUD.Seguridad'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'AUD.ValidarPlacaCamara'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'AUT.AcuerdoDetalle_2'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'AUT.Acuerdo_2'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'AUT.Tarifa_2'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Administracion.Auditoria'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Administracion.Tabla'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Administracion.TablaValor'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Administracion.TablaValorSincronizacion'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Apis.ApiToken'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'AppServicios.UsuarioZona'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Auditoria.AcuerdoDetallePaquete_2'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Auditoria.AgMaritimaWS'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Auditoria.AutRetiroPlacaChofer'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Auditoria.AutorizacionRetiro_Renovacion'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Auditoria.AutorizacionesRetiro_Choferes'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Auditoria.Booking'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Auditoria.BookingDetalle'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Auditoria.Contrato'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Auditoria.ContratoDetalle'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Auditoria.DocumentoOrigen'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Auditoria.DocumentoOrigenDetalle'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Auditoria.EnvioAlertas'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Auditoria.EnvioFastRM'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Auditoria.Logeo'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Auditoria.LogeoExtranet'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Auditoria.Precintos'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Auditoria.SolicitudAre'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Auditoria.SolicitudAreDet'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Auditoria.SolicitudAreDetLig'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Auditoria.SolicitudDetalle_RELE'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Auditoria.Solicitud_RELE'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Auditoria.StockContenedores'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Auditoria.Tarifa'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Auditoria.Tarja'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Auditoria.TrackOneWS'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Bicasa_Comercio_Exterior_Entidad'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Bicasa_Comercio_Exterior_Operador'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Bicasa_Comercio_Exterior_Operador_Persona'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Bicasa_DescargaWebDuaCab'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Bicasa_DescargaWebDuaCab_Log'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Bicasa_DescargaWebDuaDet'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Bicasa_Senasa_Categoria_Riesgo'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Bicasa_Senasa_Codigo_Institucional'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Bicasa_Senasa_Mercancia_Regulada'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Bicasa_Senasa_Subdireccion_Competente'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Boton'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'BotonMenu'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'COM.AcuerdoDetalleHorario_2'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'COM.AcuerdoDetallePaquete_2'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'COM.AcuerdoDetalle_2'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'COM.Acuerdo_2'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'COM.ClienteSinPresencia'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'COM.Descuento_2'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'COM.Modalidad_2'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'COM.ServiciosOperacionalesEnSLI_Cantidades'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'COM.SolicitudClientes'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'COM.SolicitudClientes_cant_trabajadores'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'COM.SolicitudClientes_doc_adjuntos'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'COM.SolicitudClientes_represe_legal'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'COM.SolicitudClientes_terminales'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'COM.TarifaHorarioNormal_2'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'COM.TarifaPaquete_2'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'COM.Tarifa_2'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'COM.TipoCambioPreferente'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'COMERCIAL.cab_liquidacion'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'COMERCIAL.cab_registrofactura'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'COMERCIAL.centrocosto'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'COMERCIAL.det_liquidacion'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'COMERCIAL.det_registrofactura'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'COM_APROBADORES_SOLICITUD_BASC'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'COM_SolicitudClientVas_Aprobaciones'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Comercial.AutorizacionRetiroDocumento'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Comercial.BloqueoCliente'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Comercial.Cliente'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Comercial.ClienteCorreo'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Comercial.ClienteRol'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Comercial.Contrato'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Comercial.ContratoDetalle'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Comercial.ContratoDetalleGrupo'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Comercial.Cotizacion'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Comercial.CotizacionDetalle'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Comercial.DocsComisionista'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Comercial.HistoricoReasignacion'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Comercial.Servicio'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Comercial.Tarifa'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Comercial.TipoDeCambio'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Comercial.Vendedor'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Comercial_T.AcuerdoComision'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Comercial_T.Comisionista'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Comercial_T.Liquidacion'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Comercial_T.LiquidacionDetalle'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Comercial_T.LiquidacionSustentos'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Comercial_T.TablasComunes'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Csin.BitacoraIngreso'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Csin.PaseVehicular'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'DAS.AgenciaAduana'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'DAS.Balanza'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'DAS.Bloqueos'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'DAS.Chofer'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'DAS.Clientes'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'DAS.Comercial_TarifaxTipoEsp'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'DAS.DuaIngreso'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'DAS.DuaLevante'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'DAS.DuaxOperacion'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'DAS.EmpTransporte'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'DAS.EnvioAduana'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'DAS.Numerador'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'DAS.Operacion_Cab'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'DAS.Operacion_Cab_Ubicacion'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'DAS.Operacion_Det'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'DAS.Operacion_Det_CNT'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'DAS.Operacion_Det_Lig'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'DAS.Operacion_Periodo'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'DAS.Operacion_Periodo_Dia'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'DAS.Operacion_SustentoFact'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'DAS.Retiro_Cab'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'DAS.Retiro_Det'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'DAS.SaldosManuales'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'DAS.TablasValor'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'DAS.Tarja'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'DAS.TipoCambio'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'DOC.AnticipadoCab'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'DOC.AnticipadoDet'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'DOC.AutRetiroDespachador'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'DOC.AutRetiroPlacaChofer'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'DOC.AutorizacionRetiroExtranet'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'DOC.Despachador_2'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'DOC.TarifasImo'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'DOC_CdlDiferencias'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'DescargaWeb.Chofer'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'DescargaWeb.Cliente'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'DescargaWeb.Dua'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Doc.CodigoVerificarExtranet'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.Aduana'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.AutorizacionRetiro'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.AutorizacionRetiroBloqueo'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.AutorizacionRetiroDetalle'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.AutorizacionRetiroDocumento'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.Banco'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.Booking'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.BookingDetalle'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.Carga'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.CargaSeparada'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.ClaveNSIGAD'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.ConsolidacionBooking'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.Desglose'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.Despachador'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.DespachadorSincronizacion'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.DocumentoOrigen'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.DocumentoOrigenComiso'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.DocumentoOrigenDetalle'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.DocumentoOrigenProvisional'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.DocumentoOrigenProvisionalDetalle'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.Dua'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.DuaDetalle'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.DuaOrdenEmbarque'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.DuaOrdenEmbarqueDetalle'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.DuaPartidaSenasa'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.DuaProvisional'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.EnvioAutoliquidacion'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.EnvioDuaEmbarque'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.EnvioIRM'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.EnvioNSIGAD'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.EnvioRelacionDescarga'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.EnvioRelacionEmbarque'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.EnvioSEIDAEstructura'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.EstructuraAduana'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.Expediente'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.ExpedienteDetalle'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.ExpedienteDetalle_V2'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.Expediente_V2'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.Inmovilizacion'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.InmovilizacionDetalle'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.LineaMaritima'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.Nave'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.NaveViaje'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.NaveViajeProvisional'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.NumeradorDuaEmbarque'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.Pais'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.PartidaSenasa'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.PublicarDocumento'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.Puerto'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.Regimen'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.SINISunat'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.SiniPrevio'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.SituacionDocumentoOrigenDetalle'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.TipoCarga'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.TipoEmbalaje'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion.Volante'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion_T.LecturaDua'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Documentacion_T.VolanteWebIntento'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'EXTRANET.AUDITORIA_INGRESOCARGA'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'EXTRANET.Archivos_ConsolidadosRefrendo'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'EXTRANET.ConsolidadosDAM_Temporal'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'EXTRANET.ContenedorRegistro'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'EXTRANET.DAM_ConsolidadosRefrendo'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'EXTRANET.PreLiqOnlDetalleValidacion'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'EXTRANET.PreLiqOnlServicios'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'EXTRANET.PreLiquidacionOnline'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'EXTRANET.Refrendo_Archivos'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'EXTRANET.SolicitudDetalle_RELE'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'EXTRANET.Solicitud_RELE'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'EquivalenciaCntSunat'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Extranet.CondicionesUso'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Extranet.ControlIndicador'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Extranet.ControlPeriodo'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Extranet.ControlPeriodo_Log'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Extranet.DataInicio'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Extranet.DataManual'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Extranet.ObjetivoIndicador'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Extranet.ObservacionIngreso01'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Extranet.ObservacionIngreso02'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Extranet.Presupuesto'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Extranet.RegistroIngresoTransportista'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Extranet.SolicitudAre'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Extranet.SolicitudAreDet'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Extranet.SolicitudAreDetLig'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Extranet.SolicitudIngresoCarga'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Extranet.SolicitudIngresoDetalleCarga'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Extranet.SolicitudIngresoDocumentoAdjunto'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Extranet.SolicitudIngresoTransportista'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Extranet.SolicitudServicio'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Extranet.SolicitudServicioDetalle'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Extranet.TipoIndicador'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'FNX_AUDITORIA_IVA'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'FNX_Auditoria_Orden_Servicio_Detalle'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'FNX_COREOR_MSC'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'FNX_ENVIOFAST_RC'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'FNX_ENVIOFAST_RM'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'FNX_ENVIOIVA'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'FNX_ENVIOOSIMP'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'FNX_ENVIOOSIMP_HISTORICO'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'FNX_ENVIOS_MSC'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'FNX_ERRORFAST_RC'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'FNX_ERRORFAST_RM'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'FNX_ERRORIVA'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'FNX_ERROROPEUSUAL'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'FNX_ISO_CONTENEDORES'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'FNX_LiquidacionProveedor'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'FNX_LiquidacionProveedorDetalle'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'FNX_SERVICIOS_OPERATIVOS'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'FNX_SUBTIPOOPERACION_OPEUSU'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'FNX_TIPOOPERACION_OPEUSU'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'FNX_TIPOOPEUSU'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'FNX_UBL_TRACCION'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'FNX_UBL_TRANSPORTE_ValRef'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Facturacion.DiasCredito'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Facturacion.DocumentoPago'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Facturacion.DocumentoPagoCancelacion'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Facturacion.DocumentoPagoCreditoDebito'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Facturacion.DocumentoPagoDetalle'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Facturacion.DocumentoPagoServicio'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Facturacion.Liquidacion'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Facturacion.LiquidacionDetalle'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Facturacion.LiquidacionDua'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Facturacion.NotaCredito'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Facturacion.NotaCreditoDetalle'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Facturacion.NotaDebito'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Facturacion.NotaDebitoDetalle'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Facturacion.NotaDebito_Servicio'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Facturacion.Pago'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Facturacion.Serie'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Facturacion.SerieUsuario'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Grupo'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'GrupoMenu'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Historico_Permissoes'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Historico_Permissoes_Objetos'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Menu'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'MenuBotonesAcceso'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Mkt_Tabla_Auxiliar_Reportes'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'OPE.AppRegistroContenedor'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'OPE.CargarImagenOrdenServicio'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'OPE.Chofer_2'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'OPE.DDirectaCab'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'OPE.DDirectaDet'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'OPE.MemoDevCNT'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'OPE.MemoDevCNTDetalle'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'OPE.OrdenServicioDetalle_2'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'OPE.OrdenServicioDetalle_2Archivo'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'OPE.OrdenServicioDetalle_2Sincronizacion'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'OPE.OrdenServicio_2'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'OPE.OrdenServicio_2Sincronizacion'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'OPE.ProgramacionDetLCL'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'OPE.ProgramacionLCL'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'OPE.ProveedorServicio'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'OPE.ProveedorServicioSincronizacion'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'OPE.SelloAgua'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'OPE.TranqueraManual'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'OPE.TransporteCab'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'OPE.TransporteDet'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'OPE.Ubigeo'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'OPE.Vehiculo_2'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'OPE.ZonaServicio'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'OPE_AUD_ServicioRechazo'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Ope.DetalleContenedor_Refrendo'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Ope.TableUsoArea_CargaSuelta'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.AccesoriosVehiculo'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.Actas'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.AsignacionContenedor'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.Bitacora'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.CapacidadesServicios'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.Chofer'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.ConfiguracionVehicular'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.Contenedor'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.ControlSalidaAlmacen'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.CubicajeCargaSuelta'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.CubicajeCargaSueltaDetalle'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.Especialista'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.Faltante_Sobrante'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.Faltante_Sobrante_Detalle'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.FotosActa'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.FotosApertura'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.GuiaRemision'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.GuiaRemisionDetalle'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.InformeOperativo'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.Inspector'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.Inventario_CargaMalEstado'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.Inventario_CargaMalEstado_Detalle'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.Mob_PesajeCargaSuelta'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.MovimientoBalanza'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.MovimientoBalanzaCargaSuelta'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.MovimientoBalanzaContenedor'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.MovimientoBalanzaDocumento'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.Muestra'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.OrdenServicio'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.OrdenServicioDetalle'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.Precintos'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.PresupuestoPorteo'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.Previo'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.PrevioDetalle'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.ProduccionTransporte'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.ProgramacionApertura'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.ProgramacionAperturaDetalle'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.ProgramacionApertura_'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.ProgramacionRetiros'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.ReeferTemperaturaDet'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.ServicioCatalogo'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.ServicioOperativo'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.ServicioTX'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.StockCarga'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.StockContenedores'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.Tarja'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.TarjaEir'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.TarjaEirDano'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.TarjaVehiculo'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.TarjaVehiculoDano'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.TipoDanos'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.Ubicacion'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.UbicacionDano'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.Vehiculo'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion.Zona'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion_T.BalanzaRuta'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion_T.PesoBalanzaLog'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion_T.RangoPermanencia'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Operacion_T.TiempoEstadiaExcedido'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'PRO.ListaNegraChoferes'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'PRO.ListaNegraVehiculos'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'PRO.PermisoIngresoSeguridad'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'PRO.RespuestasReniec'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'RestDjangoApi_company'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Resumen.DataIndicador'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Resumen.EmbarquesDiarios'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Resumen.MovimientoDiario'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Resumen.TiempoAtencion'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Resumen.TransmisionesDiarias'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Resumen_Servicio'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'RolSeguridad'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'RolUsuarioSeguridad'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Seguridad.AlertaICE'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Seguridad.ConfigExtranet'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Seguridad.HistorialClavesExtranet'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Seguridad.Menu'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Seguridad.Usuario'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Seguridad.UsuarioMenu'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Seguridad.UsuarioPermisosExonerados'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Seguridad.usuarioPermisos'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'SeguridadZona'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'TEMP.Volantes2016'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'TEST-20210605'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'TEST-20210609'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'TEST-20210615'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'TEST-20210616'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'TEST-OPENTRN-20210617'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'T_BLXDeposito'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'T_ContenedoresSeleccionados'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'T_Manifiesto'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'T_ManifiestoCarga'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'T_ManifiestoDetalle'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'T_ManifiestosSeleccionados'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Temp#'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'TmpLista'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Usuario'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'UsuarioSeguridad'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Usuario_Movil'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Usuario_Web'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'django_content_type'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'django_migrations'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'fenix_CodSena'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'fenix_ErrorIVA'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'fenix_dirAutomatiCont'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'reciclaje'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'sysdiagrams'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'temp4#'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'tmp_Operacion_Det'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'ws_interface'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'ws_parametrolog'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'ws_parametrotrama'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'ws_webservicecontrol'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
