# Generated by Django 3.2.6 on 2021-10-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestDjangoApi', '0002_auto_20211012_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario', models.CharField(max_length=100)),
            ],
        ),
    ]
